name: Run Data Science Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy repository to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "."
          target: "/home/vagrant/ds-pipeline-code"

      - name: Build and tag Docker image on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/vagrant/ds-pipeline-code  # Navigate to the directory where the code is copied
            docker build --cache-from=datascience-pipeline:latest -t datascience-pipeline:latest .  # Build the Docker image

  deploy_containers:
    needs: build  # Ensure that this job runs after the deploy job 
    runs-on: ubuntu-latest
    steps:
      - name: SSH and restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/vagrant/mlflow  # Navigate to the directory with the docker-compose.yml
            docker-compose up -d --no-deps project # Restart project service without dependencies
            docker-compose up  --build --no-deps model_serving # Restart model_serving service without dependencies