name: SSH Remote Commands
on:
  push:
    branches:
      - main 

jobs:
  ssh-remote-commands:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Execute SSH Command
      run: |
        ssh -p ${{ secrets.EC2_PORT }} vagrant@${{ secrets.EC2_HOST }} "echo 'Hello, World!'"
      env:
        USER: vagrant